/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.79
 * Generated at: 2022-07-19 04:56:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import com.kh.community.model.vo.Community;
import com.kh.notice.model.vo.Notice;
import com.kh.member.model.vo.Member;
import com.kh.board.model.vo.Attachment2;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1657874871187L));
    _jspx_dependants.put("/views/common/header.jsp", Long.valueOf(1657875236666L));
    _jspx_dependants.put("/views/common/footer.jsp", Long.valueOf(1657108742000L));
    _jspx_dependants.put("jar:file:/C:/Users/김유미/Desktop/SemiProject_PETMILY2/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/SemiProject/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.kh.board.model.vo.Attachment2");
    _jspx_imports_classes.add("com.kh.notice.model.vo.Notice");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("com.kh.community.model.vo.Community");
    _jspx_imports_classes.add("com.kh.member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	ArrayList<Community> adoptionReviewList = (ArrayList<Community>)request.getAttribute("adoptionReviewList");
	ArrayList<Community> volunteerReviewList = (ArrayList<Community>)request.getAttribute("volunteerReviewList");
	ArrayList<Notice> noticeList = (ArrayList<Notice>)request.getAttribute("noticeList");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>PETMILY - 메인</title>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("	/* 전체 페이지 크기 */\r\n");
      out.write("	#wrap {\r\n");
      out.write("		width: 1200px;\r\n");
      out.write("		height: auto;\r\n");
      out.write("		margin: 0 auto;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	/* content */\r\n");
      out.write("	/* content > content-area-1 */\r\n");
      out.write("	#content-area-1 {height: 400px;}\r\n");
      out.write("	\r\n");
      out.write("	/* content > content-area-2 */\r\n");
      out.write("	#content-area-2 {\r\n");
      out.write("		background-color: rgb(255, 246, 218);\r\n");
      out.write("		height: 530px;\r\n");
      out.write("	}\r\n");
      out.write("	#content-area-2 > div {\r\n");
      out.write("		height: 100%;\r\n");
      out.write("		float: left;\r\n");
      out.write("	}\r\n");
      out.write("	#content-2-1 {width: 700px;}\r\n");
      out.write("	#adopt-review-board {\r\n");
      out.write("		height: 500px;\r\n");
      out.write("		margin-top: 20px;\r\n");
      out.write("		margin-left: 20px;\r\n");
      out.write("	}\r\n");
      out.write("	#adopt-review-board > a {\r\n");
      out.write("		color: black;\r\n");
      out.write("		font-size: 20px;\r\n");
      out.write("		font-weight: bold;\r\n");
      out.write("		text-decoration: none;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	#content-2-2 {width: 500px;}\r\n");
      out.write("	#notice-review-board {\r\n");
      out.write("		height: 275px;\r\n");
      out.write("		margin-top: 20px;\r\n");
      out.write("		margin-left: 20px;\r\n");
      out.write("		margin-right: 20px;\r\n");
      out.write("	}\r\n");
      out.write("	#notice-review-board > a {\r\n");
      out.write("		color: black;\r\n");
      out.write("		font-size: 20px;\r\n");
      out.write("		font-weight: bold;\r\n");
      out.write("		text-decoration: none;\r\n");
      out.write("	}\r\n");
      out.write("	#adopt-volunteer-button {\r\n");
      out.write("		height: 235px;\r\n");
      out.write("		display: flex;\r\n");
      out.write("	}\r\n");
      out.write("	#adopt-volunteer-button > div {\r\n");
      out.write("		background-color: white;\r\n");
      out.write("		width: 460px;\r\n");
      out.write("		height: 195px;\r\n");
      out.write("		margin: auto;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	/* content > content-area-3 */\r\n");
      out.write("	#content-area-3 {\r\n");
      out.write("		background-color: rgb(243, 243, 243);\r\n");
      out.write("		height: 360px;\r\n");
      out.write("	}\r\n");
      out.write("	#content-3-1 {\r\n");
      out.write("		width: 100%;\r\n");
      out.write("		height: 100%;\r\n");
      out.write("		display: flex;\r\n");
      out.write("	}\r\n");
      out.write("	#volunteer-review-board {\r\n");
      out.write("		padding-top: 20px;\r\n");
      out.write("		padding-left: 20px;\r\n");
      out.write("		padding-right: 20px;\r\n");
      out.write("		width: 100%;\r\n");
      out.write("		\r\n");
      out.write("	}\r\n");
      out.write("	#volunteer-review-board > div {\r\n");
      out.write("		display: flex;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	#volunteer-review-board > a {\r\n");
      out.write("		color: black;\r\n");
      out.write("		font-size: 20px;\r\n");
      out.write("		font-weight: bold;\r\n");
      out.write("		text-decoration: none;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	/* 입양후기 관련 */\r\n");
      out.write("	.adopt-review-board-wrap {\r\n");
      out.write("		width: 136px;\r\n");
      out.write("		height: 212px;\r\n");
      out.write("		float: left;\r\n");
      out.write("		margin-top: 15px;\r\n");
      out.write("		margin-left: 17px;\r\n");
      out.write("		margin-right: 17px;\r\n");
      out.write("	}\r\n");
      out.write("	.adopt-review-board-wrap:hover {\r\n");
      out.write("		cursor: pointer;\r\n");
      out.write("	}\r\n");
      out.write("	.adopt-review-board-wrap > div {\r\n");
      out.write("		margin-top: 6px;\r\n");
      out.write("	}\r\n");
      out.write("	.adopt-review-board-image {\r\n");
      out.write("		width: 136px;\r\n");
      out.write("		height: 136px;\r\n");
      out.write("	}\r\n");
      out.write("	.adopt-review-board-title {\r\n");
      out.write("		font-weight: bold;\r\n");
      out.write("		overflow: hidden;\r\n");
      out.write("		text-overflow: ellipsis;\r\n");
      out.write("		white-space: nowrap;\r\n");
      out.write("	}\r\n");
      out.write("	.adopt-review-board-content {\r\n");
      out.write("		overflow: hidden;\r\n");
      out.write("		text-overflow: ellipsis;\r\n");
      out.write("		font-size: 12px;\r\n");
      out.write("		display: -webkit-box;\r\n");
      out.write("		-webkit-line-clamp: 2;\r\n");
      out.write("		-webkit-box-orient: vertical;\r\n");
      out.write("	}\r\n");
      out.write("	.adopt-review-board-no {\r\n");
      out.write("		display: none;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	/* 봉사후기 관련 */\r\n");
      out.write("	.volunteer-review-board-wrap {\r\n");
      out.write("		width: 255px;\r\n");
      out.write("		height: 260px;\r\n");
      out.write("		float: left;\r\n");
      out.write("		margin-top: 30px;\r\n");
      out.write("		margin-left: 17px;\r\n");
      out.write("		margin-right: 17px;\r\n");
      out.write("	}\r\n");
      out.write("	.volunteer-review-board-wrap:hover {\r\n");
      out.write("		cursor: pointer;\r\n");
      out.write("	}\r\n");
      out.write("	.volunteer-review-board-wrap > div {\r\n");
      out.write("		margin-top: 6px;\r\n");
      out.write("	}\r\n");
      out.write("	.volunteer-review-board-image {\r\n");
      out.write("		width: 255px;\r\n");
      out.write("		height: 160px;\r\n");
      out.write("	}\r\n");
      out.write("	.volunteer-review-board-title {\r\n");
      out.write("		font-weight: bold;\r\n");
      out.write("		overflow: hidden;\r\n");
      out.write("		text-overflow: ellipsis;\r\n");
      out.write("		white-space: nowrap;\r\n");
      out.write("	}\r\n");
      out.write("	.volunteer-review-board-content {\r\n");
      out.write("		overflow: hidden;\r\n");
      out.write("		text-overflow: ellipsis;\r\n");
      out.write("		font-size: 12px;\r\n");
      out.write("		display: -webkit-box;\r\n");
      out.write("		-webkit-line-clamp: 3;\r\n");
      out.write("		-webkit-box-orient: vertical;\r\n");
      out.write("	}\r\n");
      out.write("	.volunteer-review-board-no {\r\n");
      out.write("		display: none;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	/* 공지사항 관련 */\r\n");
      out.write("	.notice-table {\r\n");
      out.write("		width: 460px;\r\n");
      out.write("		table-layout: fixed;\r\n");
      out.write("		border-collapse: collapse;\r\n");
      out.write("	}\r\n");
      out.write("	.notice-table tr {\r\n");
      out.write("		border-bottom: 1px solid black;\r\n");
      out.write("		height: 38px;\r\n");
      out.write("	}\r\n");
      out.write("	.notice-table tr:hover {\r\n");
      out.write("		font-weight: bold;\r\n");
      out.write("		cursor: pointer;\r\n");
      out.write("	}\r\n");
      out.write("	.notice-table .notice-table-no {\r\n");
      out.write("		display: none;\r\n");
      out.write("	}\r\n");
      out.write("	.notice-table .notice-table-title {\r\n");
      out.write("		overflow: hidden;\r\n");
      out.write("		text-overflow: ellipsis;\r\n");
      out.write("		white-space: nowrap;\r\n");
      out.write("		width: 80%;\r\n");
      out.write("	}\r\n");
      out.write("	.notice-table .notice-table-date {\r\n");
      out.write("		width: 20%;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	#adopt-volunteer-button {\r\n");
      out.write("		text-align: center;\r\n");
      out.write("		\r\n");
      out.write("	}\r\n");
      out.write("	#adopt-volunteer-button > div > div {\r\n");
      out.write("		margin-top: 8px;\r\n");
      out.write("	}\r\n");
      out.write("	#adopt-volunteer-button > div > div > hr {\r\n");
      out.write("		width: 420px;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<div id=\"wrap\">\r\n");
      out.write("\r\n");
      out.write("		<!-- header -->\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	Member loginUser = (Member)session.getAttribute("loginUser");
	String alertMsg = (String)session.getAttribute("alertMsg");
	String contextPath = request.getContextPath();
	Attachment2 at2 = (Attachment2)session.getAttribute("at");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>header</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("	/* header */\r\n");
      out.write("	#header {height: 100px;}\r\n");
      out.write("	#header > div {\r\n");
      out.write("		height: 100%;\r\n");
      out.write("		float: left;\r\n");
      out.write("		box-sizing: border-box;\r\n");
      out.write("	}\r\n");
      out.write("	#header a {text-decoration: none;}\r\n");
      out.write("\r\n");
      out.write("	/* header > login-area */\r\n");
      out.write("	#logo-area {\r\n");
      out.write("		width: 250px;\r\n");
      out.write("		text-align: center;\r\n");
      out.write("	}\r\n");
      out.write("	#logo {\r\n");
      out.write("		width: 200px;\r\n");
      out.write("		margin: auto;\r\n");
      out.write("		margin-top: 10px;\r\n");
      out.write("	}\r\n");
      out.write("	#logo > a {\r\n");
      out.write("		color: rgb(232, 191, 123);\r\n");
      out.write("		font-size: 50px;\r\n");
      out.write("		font-weight: bold;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	/* header > menubar-area */\r\n");
      out.write("	#menubar-area {\r\n");
      out.write("		width: 660px;\r\n");
      out.write("		padding-top: 60px;\r\n");
      out.write("		text-align: center;\r\n");
      out.write("	}\r\n");
      out.write("	#menubar {margin-right: 10px;}\r\n");
      out.write("	#menubar > a {\r\n");
      out.write("		color: black;\r\n");
      out.write("		font-size: 23px;\r\n");
      out.write("		font-weight: bold;\r\n");
      out.write("		margin-left: 35px;\r\n");
      out.write("		margin-right: 35px;\r\n");
      out.write("	}\r\n");
      out.write("	#menubar > a:hover {color: rgb(155, 128, 82);}\r\n");
      out.write("\r\n");
      out.write("	/* header > login-area */\r\n");
      out.write("	#login-area {width: 290px;}\r\n");
      out.write("	#login-area > div {box-sizing: border-box;}\r\n");
      out.write("	#login-info {\r\n");
      out.write("		width: 100%;\r\n");
      out.write("		height: 60px;\r\n");
      out.write("		color: black;\r\n");
      out.write("		font-size: 18px;\r\n");
      out.write("		font-weight: bold;\r\n");
      out.write("		text-align: left;\r\n");
      out.write("		display: flex;\r\n");
      out.write("	}\r\n");
      out.write("	#login-info > div {\r\n");
      out.write("		height: 100%;\r\n");
      out.write("		line-height: 57.33px;\r\n");
      out.write("		float: left;\r\n");
      out.write("	}\r\n");
      out.write("	#profile {\r\n");
      out.write("		width: 22%;\r\n");
      out.write("		display: flex;\r\n");
      out.write("		margin-left: 10px;\r\n");
      out.write("	}\r\n");
      out.write("	#profile > img {\r\n");
      out.write("		border: 1px solid rgb(125, 125, 125);\r\n");
      out.write("		border-radius: 70%;\r\n");
      out.write("		margin: auto;\r\n");
      out.write("	}\r\n");
      out.write("	#user-class {\r\n");
      out.write("		width: 30%;\r\n");
      out.write("		text-align: center;\r\n");
      out.write("	}\r\n");
      out.write("	#user-nickname {\r\n");
      out.write("		width: 48%;\r\n");
      out.write("		overflow: hidden;\r\n");
      out.write("		text-overflow: ellipsis;\r\n");
      out.write("	}\r\n");
      out.write("	#login-menu {text-align: center;}\r\n");
      out.write("	#login-menu > a {color: rgb(125, 125, 125);}\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	\r\n");
      out.write("	<script>\r\n");
      out.write("	\r\n");
      out.write("		// 얼럿 띄우기(공용)\r\n");
      out.write("		var msg = \"");
      out.print( alertMsg );
      out.write("\";\r\n");
      out.write("		\r\n");
      out.write("		if (msg != \"null\") {\r\n");
      out.write("\r\n");
      out.write("			alert(msg);\r\n");
      out.write("			");
 session.removeAttribute("alertMsg"); 
      out.write("\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("	<!-- header -->\r\n");
      out.write("	<div id=\"header\">\r\n");
      out.write("\r\n");
      out.write("		<!-- 로고 -->\r\n");
      out.write("		<div id=\"logo-area\">\r\n");
      out.write("			<div id=\"logo\">\r\n");
      out.write("				<a href=\"");
      out.print( contextPath );
      out.write("\">PETMILY</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- 메인메뉴 -->\r\n");
      out.write("		<div id=\"menubar-area\">\r\n");
      out.write("			<div id=\"menubar\">\r\n");
      out.write("				<a href=\"");
      out.print(contextPath);
      out.write("/main.ad?cpage=1\">입양하기</a>\r\n");
      out.write("				<a href=\"");
      out.print(contextPath);
      out.write("/main.vl?cpage=1\">봉사하기</a>\r\n");
      out.write("				<a href=\"\">굿즈샵</a>\r\n");
      out.write("				");
 if(loginUser!=null){ 
      out.write("\r\n");
      out.write("					<a href=\"");
      out.print(contextPath);
      out.write("/list.as?cpage=1\">고객센터</a>\r\n");
      out.write("				");
} else{ 
      out.write("\r\n");
      out.write("					<a onclick=\"loginBlock()\">고객센터</a>			\r\n");
      out.write("				");
} 
      out.write("\r\n");
      out.write("				\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		<script>\r\n");
      out.write("			function loginBlock(){\r\n");
      out.write("				alert(\"로그인 후 이용할 수 있는 서비스입니다.\");\r\n");
      out.write("			}\r\n");
      out.write("		\r\n");
      out.write("		</script>\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		<!-- 로그인 상태에 보여지는 login-area -->\r\n");
      out.write("		");
 if(loginUser != null) { 
      out.write("\r\n");
      out.write("		\r\n");
      out.write("			<div id=\"login-area\">\r\n");
      out.write("\r\n");
      out.write("				<!-- 로그인 정보 표시(프로필 사진, 회원등급, 닉네임) -->\r\n");
      out.write("				<div id=\"login-info\">\r\n");
      out.write("\r\n");
      out.write("					<!-- 프로필 사진 -->\r\n");
      out.write("					<div id=\"profile\">\r\n");
      out.write("                        ");
 if(at2 == null) { 
      out.write("\r\n");
      out.write("                        <img class=\"profileImg\" src=\"");
      out.print( contextPath );
      out.write("/resources/blank-profile-picture.png\" height=\"70%\">\r\n");
      out.write("                        ");
 } else { 
      out.write("\r\n");
      out.write("                        <img class=\"profileImg\" src=\"");
      out.print( contextPath );
      out.write('/');
      out.print( at2.getFilePath()+at2.getChangeName() );
      out.write("\" height=\"70%\">\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("					<!-- 회원등급 -->\r\n");
      out.write("					<div id=\"user-class\">\r\n");
      out.write("						");
 
							String userClass = "";
						
							switch (loginUser.getUserClass()) {
							
								case "A" : userClass = "관리자"; break;
								case "G" : userClass = "단체"; break;
								case "P" : userClass = "일반"; break;
							}
						
      out.write("\r\n");
      out.write("						[");
      out.print( userClass );
      out.write("]\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<!-- 닉네임 -->\r\n");
      out.write("					<div id=\"user-nickname\">\r\n");
      out.write("						");
      out.print( loginUser.getUserNickname() );
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("					\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<!-- 로그인 시 보여지는 login-menu -->\r\n");
      out.write("				<div id=\"login-menu\">\r\n");
      out.write("					<a href=\"");
      out.print( contextPath );
      out.write("\">HOME</a>\r\n");
      out.write("					&nbsp;&nbsp;&vert;&nbsp;&nbsp;\r\n");
      out.write("					<a href=\"");
      out.print( contextPath );
      out.write("/myPage.me\">마이페이지</a>\r\n");
      out.write("					&nbsp;&nbsp;&vert;&nbsp;&nbsp;\r\n");
      out.write("					<a href=\"");
      out.print( contextPath );
      out.write("/logout.me\">로그아웃</a>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("		<!-- 비회원 상태에 보여지는 login-area -->\r\n");
      out.write("		");
 } else { 
      out.write("\r\n");
      out.write("		\r\n");
      out.write("			<div id=\"login-area\">\r\n");
      out.write("\r\n");
      out.write("				<!-- 로그인 정보 표시(비회원이라 내용 없음) -->\r\n");
      out.write("				<div id=\"login-info\">\r\n");
      out.write("					<div id=\"profile-picture\"></div>\r\n");
      out.write("					<div id=\"user-nickname\"></div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<!-- 비회원 시 보여지는 login-menu -->\r\n");
      out.write("				<div id=\"login-menu\">\r\n");
      out.write("					<a href=\"");
      out.print( contextPath );
      out.write("\">HOME</a>\r\n");
      out.write("					&nbsp;&nbsp;&vert;&nbsp;&nbsp;\r\n");
      out.write("					<a href=\"");
      out.print( contextPath );
      out.write("/enrollForm.me\">회원가입</a>\r\n");
      out.write("					&nbsp;&nbsp;&vert;&nbsp;&nbsp;\r\n");
      out.write("					<a href=\"");
      out.print( contextPath );
      out.write("/loginForm.me\">로그인</a>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("		");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- content -->\r\n");
      out.write("		<div id=\"content\">\r\n");
      out.write("\r\n");
      out.write("			<div id=\"content-area-1\">\r\n");
      out.write("				<div>\r\n");
      out.write("					<img src=\"");
      out.print( contextPath );
      out.write("/resources/banner-picture.png\" alt=\"\">\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div id=\"content-area-2\">\r\n");
      out.write("				<div id=\"content-2-1\">\r\n");
      out.write("					<div id=\"adopt-review-board\">\r\n");
      out.write("						<a href=\"");
      out.print( contextPath );
      out.write("/reviewlist.ad?cpage=1\">입양후기</a> <hr>\r\n");
      out.write("\r\n");
      out.write("						");
 if(adoptionReviewList.isEmpty()) { 
      out.write("\r\n");
      out.write("\r\n");
      out.write("							<p>등록된 입양후기 게시글이 없습니다.</p>\r\n");
      out.write("\r\n");
      out.write("						");
 } else { 
      out.write("\r\n");
      out.write("\r\n");
      out.write("							");
 for(Community c : adoptionReviewList) { 
      out.write("\r\n");
      out.write("\r\n");
      out.write("								<div class=\"adopt-review-board-wrap\">\r\n");
      out.write("									<img class=\"adopt-review-board-image\" src=\"");
      out.print( c.getTitleImg() );
      out.write("\">\r\n");
      out.write("									<div class=\"adopt-review-board-no\">\r\n");
      out.write("										");
      out.print( c.getComNo() );
      out.write("\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"adopt-review-board-title\">\r\n");
      out.write("										");
      out.print( c.getTitle() );
      out.write("\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"adopt-review-board-content\">\r\n");
      out.write("										");
      out.print( c.getSummary() );
      out.write("\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("							");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("						");
 } 
      out.write("\r\n");
      out.write("						\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div id=\"content-2-2\">\r\n");
      out.write("					<div id=\"notice-review-board\">\r\n");
      out.write("						<a href=\"");
      out.print( contextPath );
      out.write("/list.no\">공지사항</a> <hr>\r\n");
      out.write("						<table class=\"notice-table\">\r\n");
      out.write("							<tbody>\r\n");
      out.write("\r\n");
      out.write("								");
 if(noticeList.isEmpty()) { 
      out.write("\r\n");
      out.write("\r\n");
      out.write("									<p>등록된 공지사항 게시글이 없습니다.</p>\r\n");
      out.write("\r\n");
      out.write("								");
 } else { 
      out.write("\r\n");
      out.write("		\r\n");
      out.write("									");
 for(Notice n : noticeList) { 
      out.write("\r\n");
      out.write("		\r\n");
      out.write("										<tr>\r\n");
      out.write("											<td class=\"notice-table-no\">");
      out.print( n.getNoticeNo() );
      out.write("</td>\r\n");
      out.write("											<td class=\"notice-table-title\">");
      out.print( n.getNoticeTitle() );
      out.write("</td>\r\n");
      out.write("											<td class=\"notice-table-date\">");
      out.print( n.getCreateDate() );
      out.write("</td>\r\n");
      out.write("										</tr>\r\n");
      out.write("										\r\n");
      out.write("									");
 } 
      out.write("\r\n");
      out.write("		\r\n");
      out.write("								");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("							</tbody>\r\n");
      out.write("						</table>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div id=\"adopt-volunteer-button\">\r\n");
      out.write("						<div>\r\n");
      out.write("							<div>\r\n");
      out.write("								<a href=\"");
      out.print( contextPath );
      out.write("/main.ad?cpage=1\">\r\n");
      out.write("									<img src=\"");
      out.print( contextPath );
      out.write("/resources/adopt-picture.png\" width=\"90%\">\r\n");
      out.write("								</a>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div>\r\n");
      out.write("								<hr>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div>\r\n");
      out.write("								<a href=\"");
      out.print( contextPath );
      out.write("/main.vl?cpage=1\">\r\n");
      out.write("									<img src=\"");
      out.print( contextPath );
      out.write("/resources/volunteer-picture.png\" width=\"90%\">\r\n");
      out.write("								</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div id=\"content-area-3\">\r\n");
      out.write("				<div id=\"content-3-1\">\r\n");
      out.write("					<div id=\"volunteer-review-board\">\r\n");
      out.write("						<a href=\"");
      out.print( contextPath );
      out.write("/reviewlist.vl?cpage=1\">봉사후기</a>\r\n");
      out.write("						<div>\r\n");
      out.write("\r\n");
      out.write("							");
 if(volunteerReviewList.isEmpty()) { 
      out.write("\r\n");
      out.write("\r\n");
      out.write("								<p>등록된 봉사후기 게시글이 없습니다.</p>\r\n");
      out.write("	\r\n");
      out.write("							");
 } else { 
      out.write("\r\n");
      out.write("	\r\n");
      out.write("								");
 for(Community c : volunteerReviewList) { 
      out.write("\r\n");
      out.write("	\r\n");
      out.write("									<div class=\"volunteer-review-board-wrap\">\r\n");
      out.write("										<img class=\"volunteer-review-board-image\" src=\"");
      out.print( c.getTitleImg() );
      out.write("\">\r\n");
      out.write("										<div class=\"volunteer-review-board-no\">\r\n");
      out.write("											");
      out.print( c.getComNo() );
      out.write("\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"volunteer-review-board-title\">\r\n");
      out.write("											");
      out.print( c.getTitle() );
      out.write("\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"volunteer-review-board-content\">\r\n");
      out.write("											");
      out.print( c.getSummary() );
      out.write("\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("	\r\n");
      out.write("								");
 } 
      out.write("\r\n");
      out.write("	\r\n");
      out.write("							");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- footer -->\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>footer</title>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("	/* footer */\r\n");
      out.write("	#footer {\r\n");
      out.write("		background-color: rgb(158, 158, 158);\r\n");
      out.write("		height: 120px;\r\n");
      out.write("	}\r\n");
      out.write("	#footer-content {\r\n");
      out.write("		padding-top: 6px;\r\n");
      out.write("		padding-left: 20px;\r\n");
      out.write("		padding-right: 20px;\r\n");
      out.write("	}\r\n");
      out.write("	#footer-content > p {\r\n");
      out.write("		color: white;\r\n");
      out.write("		font-size: 14px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<!-- footer -->\r\n");
      out.write("	<div id=\"footer\">\r\n");
      out.write("		<div id=\"footer-content\">\r\n");
      out.write("			<p>\r\n");
      out.write("				(04540) 서울시 중구 남대문로 120 대일빌딩 2F, 3F&nbsp;&nbsp;&nbsp;대표 : 이승철\r\n");
      out.write("				<br>MAIL : petmily@gmail.com&nbsp;&nbsp;&nbsp;TEL : 02-999-1004&nbsp;&nbsp;&nbsp;FAX : 02-999-1004&nbsp;&nbsp;&nbsp;사업자등록번호 : 123-12-12345\r\n");
      out.write("				<br><br>Copyright © 2022 PETMILY All Right Reserved\r\n");
      out.write("			</p>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("        $(function(){\r\n");
      out.write("\r\n");
      out.write("            $(\".adopt-review-board-wrap\").click(function(){\r\n");
      out.write("\r\n");
      out.write("                var cno = $(this).children().eq(1).text();\r\n");
      out.write("\r\n");
      out.write("                location.href=\"");
      out.print( contextPath );
      out.write("/detail.cm?cno=\" + cno + \"&type=1\";\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("			$(\".volunteer-review-board-wrap\").click(function(){\r\n");
      out.write("\r\n");
      out.write("				var cno = $(this).children().eq(1).text();\r\n");
      out.write("\r\n");
      out.write("				location.href=\"");
      out.print( contextPath );
      out.write("/detail.cm?cno=\" + cno + \"&type=2\";\r\n");
      out.write("			});\r\n");
      out.write("			");
if(loginUser != null){
      out.write("\r\n");
      out.write("			$(\".notice-table>tbody>tr\").click(function(){\r\n");
      out.write("\r\n");
      out.write("				var nno = $(this).children().eq(0).text();\r\n");
      out.write("\r\n");
      out.write("				location.href=\"");
      out.print( contextPath );
      out.write("/detail.no?nno=\" + nno;\r\n");
      out.write("			});\r\n");
      out.write("			");
} else {
      out.write("\r\n");
      out.write("			$(\".notice-table>tbody>tr\").click(function(){\r\n");
      out.write("				alert(\"로그인 후 이용할 수 있는 서비스입니다.\");		\r\n");
      out.write("			});\r\n");
      out.write("			");
}
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        })\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
