/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.79
 * Generated at: 2022-07-07 05:41:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.kh.member.model.vo.Member;
import java.util.ArrayList;

public final class InterListPR_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.kh.member.model.vo.Member");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    \r\n");


	Member loginUser = (Member)session.getAttribute("loginUser");
	
	String contextPath = request.getContextPath();
	
	String userNickname = loginUser.getUserNickname();
		
	String userClass = loginUser.getUserClass();




      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>마이페이지</title>\r\n");
      out.write("<style>\r\n");
      out.write("        div{\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("            /* border: 1px solid darkolivegreen; */\r\n");
      out.write("        }\r\n");
      out.write("        .wrap{\r\n");
      out.write("            width: 1200px;\r\n");
      out.write("            height: 1600px;\r\n");
      out.write("            margin: auto;\r\n");
      out.write("        }\r\n");
      out.write("        .wrap > div{width: 100%;}\r\n");
      out.write("        #header{height: 10%;} \r\n");
      out.write("        #footer{height: 10%;}\r\n");
      out.write("        #navigator{height: 3%;}\r\n");
      out.write("        #content{height: 77%;}\r\n");
      out.write("\r\n");
      out.write("        /* 세부 div 속성 */\r\n");
      out.write("        #header > div, #content > div{\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            float: left;\r\n");
      out.write("        }\r\n");
      out.write("        /* 가로길이 */\r\n");
      out.write("        #header_1{width: 20%;}\r\n");
      out.write("        #header_2{width: 80%;}\r\n");
      out.write("\r\n");
      out.write("        #content_1{width: 20%;}\r\n");
      out.write("        #content_2{width: 80%;}\r\n");
      out.write("/*------------------- header_1 영역 --------------------*/\r\n");
      out.write("        #header_1{\r\n");
      out.write("            /* 영역 표시용 : 지우기 */\r\n");
      out.write("            background-color: floralwhite;\r\n");
      out.write("            color: sandybrown;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            font-size: 20px;\r\n");
      out.write("            font-weight: 900;\r\n");
      out.write("            padding-top: 50px;\r\n");
      out.write("        }\r\n");
      out.write("/*------------------- header_2 영역 --------------------*/\r\n");
      out.write("        #header_2 > #login-area{\r\n");
      out.write("            text-align: right;\r\n");
      out.write("            height: 20%;\r\n");
      out.write("        }\r\n");
      out.write("        #header_2 > #login-area a{\r\n");
      out.write("            color: black;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            font-size: 15px;\r\n");
      out.write("        }\r\n");
      out.write("        #header_2 > #menubar{\r\n");
      out.write("            height: 80%;\r\n");
      out.write("            padding: 50px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("        /* #header_2 > #menubar a{\r\n");
      out.write("            color: rgb(155, 128, 82);\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            font-size: 50px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        } */\r\n");
      out.write("        #header_2 > #menubar > pre a{\r\n");
      out.write("            color: rgb(155, 128, 82);\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            font-size: 30px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;\r\n");
      out.write("        }\r\n");
      out.write("        #header_2 > #menubar :hover{\r\n");
      out.write("            color: orange;\r\n");
      out.write("        }\r\n");
      out.write("/*------------------- navigator 영역 --------------------*/\r\n");
      out.write("        #navigator{padding-top: 10px;}\r\n");
      out.write("        #navi{height: 100%;}\r\n");
      out.write("        #navi a{\r\n");
      out.write("            color: black;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            font-size: 15px; \r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("/*------------------- content_1 영역 --------------------*/\r\n");
      out.write("        #content_1 > #user-area{\r\n");
      out.write("            height: 47%;\r\n");
      out.write("            background-color: lightgray;\r\n");
      out.write("\r\n");
      out.write("            /* 사용자영역 표시 - 지우기*/\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            padding-top: 1%;\r\n");
      out.write("            padding-left: 5%;\r\n");
      out.write("            \r\n");
      out.write("        }\r\n");
      out.write("        #content_1 > #user-area > p{\r\n");
      out.write("            \r\n");
      out.write("            font-size: 17px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            \r\n");
      out.write("        }\r\n");
      out.write("        #content_1 > #user-area > li > a {\r\n");
      out.write("            \r\n");
      out.write("            color: black;\r\n");
      out.write("\r\n");
      out.write("            text-decoration-line: none;\r\n");
      out.write("            \r\n");
      out.write("        }#content_1 > #admin-area > li > a {\r\n");
      out.write("            \r\n");
      out.write("            color: black;\r\n");
      out.write("\r\n");
      out.write("            text-decoration-line: none;\r\n");
      out.write("            \r\n");
      out.write("        }\r\n");
      out.write("        #content_1 > #br{\r\n");
      out.write("            height: 2%;\r\n");
      out.write("        }\r\n");
      out.write("        #content_1 > #admin-area{\r\n");
      out.write("            height: 25%;\r\n");
      out.write("            background-color: lightgray;\r\n");
      out.write("\r\n");
      out.write("            /* 관리자영역 표시 - 지우기*/\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            padding-top: 3%;\r\n");
      out.write("            padding-left: 5%;\r\n");
      out.write("            \r\n");
      out.write("        }\r\n");
      out.write("/*------------------- content_2 영역 --------------------*/\r\n");
      out.write("        #content_2 > #content-area{\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            margin-left: 20px;\r\n");
      out.write("            background-color: floralwhite;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("/*------------------- footer 영역 --------------------*/\r\n");
      out.write("        #footer{\r\n");
      out.write("            background-color: gray;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"wrap\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div id=\"header\">\r\n");
      out.write("            <div id=\"header_1\">\r\n");
      out.write("                로고 영역\r\n");
      out.write("            </div><!--header_1-->\r\n");
      out.write("            <div id=\"header_2\">\r\n");
      out.write("                <div id=\"login-area\">\r\n");
      out.write("                \r\n");
      out.write("                	<b>");
      out.print( userNickname );
      out.write("님 환영합니다!</b> <br><br>\r\n");
      out.write("                	<div align=\"right\">\r\n");
      out.write("                		<a href=\"");
      out.print( contextPath );
      out.write("/myPage.me\">마이페이지</a>\r\n");
      out.write("                		<a href=\"");
      out.print( contextPath );
      out.write("/logout.me\">로그아웃</a>\r\n");
      out.write("\r\n");
      out.write("                	</div>\r\n");
      out.write("                \r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"menubar\">\r\n");
      out.write("                    <!--<a href=\"#\">공지사항</a> &emsp;\r\n");
      out.write("                    <a href=\"#\">입양하기</a> &emsp;\r\n");
      out.write("                    <a href=\"#\">봉사하기</a> &emsp;\r\n");
      out.write("                    <a href=\"#\">굿즈샵</a> &emsp;\r\n");
      out.write("                    <a href=\"#\">고객센터</a>-->\r\n");
      out.write("\r\n");
      out.write("                    <pre><!--\r\n");
      out.write("                        --><a href=\"#\">공지사항</a>            <!--\r\n");
      out.write("                        --><a href=\"#\">입양하기</a>            <!--\r\n");
      out.write("                        --><a href=\"#\">봉사하기</a>            <!--\r\n");
      out.write("                        --><a href=\"#\">굿즈샵</a>            <!--\r\n");
      out.write("                        --><a href=\"#\">고객센터</a>\r\n");
      out.write("                    </pre>\r\n");
      out.write("                </div><!--header_2-->\r\n");
      out.write("            </div>\r\n");
      out.write("        </div><!--header-->\r\n");
      out.write("\r\n");
      out.write("        <hr>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"navigator\">\r\n");
      out.write("\r\n");
      out.write("            <div id=\"navi\">\r\n");
      out.write("                <!-- 임시 내용 -->\r\n");
      out.write("                <a href=\"");
      out.print( contextPath );
      out.write("\">HOME</a> > \r\n");
      out.write("                <a href=\"");
      out.print( contextPath );
      out.write("/myPage.me\">마이페이지</a> >\r\n");
      out.write("                <a href=\"");
      out.print( contextPath );
      out.write("/interListPR.bo\">관심 등록 굿즈 보기</a>\r\n");
      out.write("            </div><!--navi-->\r\n");
      out.write("\r\n");
      out.write("        </div><!--navigator-->\r\n");
      out.write("\r\n");
      out.write("        <div id=\"content\">\r\n");
      out.write("            <div id=\"content_1\">\r\n");
      out.write("                ");
 if(!(userClass.equals("A"))) { 
      out.write("\r\n");
      out.write("                    <div id=\"user-area\">\r\n");
      out.write("                        <!-- 사용자만 보이는 영역-->\r\n");
      out.write("                        ");
 if(userClass.equals("P")) { 
      out.write("\r\n");
      out.write("                            <p>회원 정보 관리</p>\r\n");
      out.write("                            <li><a href=\"");
      out.print( contextPath );
      out.write("/profile.me\">내 프로필 수정</a></li>\r\n");
      out.write("                            <li><a href=\"");
      out.print( contextPath );
      out.write("/updateForm.me\">회원 정보 수정</a></li>\r\n");
      out.write("                            <li><a href=\"");
      out.print( contextPath );
      out.write("/updatePwdForm.me\">비밀번호 변경</a></li>\r\n");
      out.write("                            <li><a href=\"");
      out.print( contextPath );
      out.write("/deletePage.me\">회원 탈퇴</a></li>\r\n");
      out.write("                           \r\n");
      out.write("                           <p>내가 쓴 글 조회</p>\r\n");
      out.write("                            <li><a href=\"");
      out.print( contextPath );
      out.write("/adoptComment.bo\">입양 후기 게시글 조회</a></li>\r\n");
      out.write("                           \r\n");
      out.write("                           <p>굿즈샵</p>\r\n");
      out.write("                            <li><a href=\"#\">장바구니</a></li>\r\n");
      out.write("                            <li><a href=\"#\">구매내역/배송조회</a></li>\r\n");
      out.write("                            <li><a href=\"#\">내가 쓴 리뷰 조회</a></li>\r\n");
      out.write("                           \r\n");
      out.write("                           <p><a href=\"");
      out.print( contextPath );
      out.write("/interList.bo\">관심 목록</a></p>\r\n");
      out.write("                            <li><a href=\"");
      out.print( contextPath );
      out.write("/interListAN.bo\">관심 등록 동물 보기</a></li>\r\n");
      out.write("                            <li><a href=\"");
      out.print( contextPath );
      out.write("/interListPR.bo\">관심 등록 굿즈 보기</a></li>\r\n");
      out.write("                           \r\n");
      out.write("                           <p>고객센터</p>\r\n");
      out.write("                            <li><a href=\"#\">1:1 문의하기</a></li>\r\n");
      out.write("                            <li><a href=\"#\">단체 신청</a></li>\r\n");
      out.write("                            <li><a href=\"#\">문의 내역</a></li>\r\n");
      out.write("                           \r\n");
      out.write("                        ");
  } else { 
      out.write("\r\n");
      out.write("                                <p>회원 정보 관리</p>\r\n");
      out.write("                                <li><a href=\"");
      out.print( contextPath );
      out.write("/profile.me\">내 프로필 수정</a></li>\r\n");
      out.write("                                <li><a href=\"");
      out.print( contextPath );
      out.write("/updateForm.me\">회원 정보 수정</a></li>\r\n");
      out.write("                                <li><a href=\"");
      out.print( contextPath );
      out.write("/updatePwdForm.me\">비밀번호 변경</a></li>\r\n");
      out.write("                                <li><a href=\"");
      out.print( contextPath );
      out.write("/deletePage.me\">회원 탈퇴</a></li>\r\n");
      out.write("                               \r\n");
      out.write("                                <p><a href=\"");
      out.print( contextPath );
      out.write("/myPost.bo\">내가 쓴 글 조회</a> </p>\r\n");
      out.write("                                <li><a href=\"");
      out.print( contextPath );
      out.write("/volunteerRecruit.bo\">봉사 활동 모집글 조회</a></li>\r\n");
      out.write("                                <li><a href=\"");
      out.print( contextPath );
      out.write("/volunteerComment.bo\">봉사 후기 게시글 조회</a></li>\r\n");
      out.write("                                <li><a href=\"");
      out.print( contextPath );
      out.write("/animalPost.bo\">동물 등록 게시글 조회</a></li>\r\n");
      out.write("                               \r\n");
      out.write("                                <p>굿즈샵</p>\r\n");
      out.write("                                <li><a href=\"#\">장바구니</a></li>\r\n");
      out.write("                                <li><a href=\"#\">구매내역/배송조회</a></li>\r\n");
      out.write("                               \r\n");
      out.write("                                <p><a href=\"");
      out.print( contextPath );
      out.write("/interList.bo\">관심 목록</a></p>\r\n");
      out.write("                                <li><a href=\"");
      out.print( contextPath );
      out.write("/interListAN.bo\">관심 등록 동물 보기</a></li>\r\n");
      out.write("                                <li><a href=\"");
      out.print( contextPath );
      out.write("/interListPR.bo\">관심 등록 굿즈 보기</a></li>\r\n");
      out.write("                               \r\n");
      out.write("                                <p>고객센터</p>\r\n");
      out.write("                                <li><a href=\"#\">1:1 문의하기</a></li>\r\n");
      out.write("                                <li><a href=\"#\">문의 내역</a></li>\r\n");
      out.write("                               </ul>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                        \r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div id=\"br\">\r\n");
      out.write("                        <!-- 사용자영역과 관리자영역 사이 공간-->\r\n");
      out.write("                    </div>\r\n");
      out.write("                ");
 } else { 
      out.write("\r\n");
      out.write("                    <div id=\"user-area\">\r\n");
      out.write("                        <p>회원 정보 관리</p>\r\n");
      out.write("                            <li><a href=\"");
      out.print( contextPath );
      out.write("/profile.me\">내 프로필 수정</a></li>\r\n");
      out.write("                            <li><a href=\"");
      out.print( contextPath );
      out.write("/updateForm.me\">회원 정보 수정</a></li>\r\n");
      out.write("                            <li><a href=\"");
      out.print( contextPath );
      out.write("/deletePage.me\">회원 탈퇴</a></li>\r\n");
      out.write("                           \r\n");
      out.write("                           <p>내가 쓴 글 조회</p>\r\n");
      out.write("                            <li><a href=\"");
      out.print( contextPath );
      out.write("/adoptComment.bo\">입양 후기 게시글 조회</a></li>\r\n");
      out.write("                           \r\n");
      out.write("                           <p>굿즈샵</p>\r\n");
      out.write("                            <li><a href=\"#\">장바구니</a></li>\r\n");
      out.write("                            <li><a href=\"#\">구매내역/배송조회</a></li>\r\n");
      out.write("                            <li><a href=\"#\">내가 쓴 리뷰 조회</a></li>\r\n");
      out.write("                           \r\n");
      out.write("                           <p><a href=\"");
      out.print( contextPath );
      out.write("/interList.bo\">관심 목록</a></p>\r\n");
      out.write("                            <li><a href=\"");
      out.print( contextPath );
      out.write("/interListAN.bo\">관심 등록 동물 보기</a></li>\r\n");
      out.write("                            <li><a href=\"");
      out.print( contextPath );
      out.write("/interListPR.bo\">관심 등록 굿즈 보기</a></li>\r\n");
      out.write("                           \r\n");
      out.write("                           <p>고객센터</p>\r\n");
      out.write("                            <li><a href=\"#\">1:1 문의하기</a></li>\r\n");
      out.write("                            <li><a href=\"#\">단체 신청</a></li>\r\n");
      out.write("                            <li><a href=\"#\">문의 내역</a></li>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div id=\"admin-area\">\r\n");
      out.write("                        <!-- 관리자가 볼 수 있는 영역-->\r\n");
      out.write("                        <p>관리자 메뉴</p>\r\n");
      out.write("                            <li><a href=\"#\">상품 등록</a></li>\r\n");
      out.write("                            <li><a href=\"#\">상품 주문내역</a></li>\r\n");
      out.write("                            <li><a href=\"#\">단체 승인</a></li>\r\n");
      out.write("                            <li><a href=\"#\">입양신청서</a></li>\r\n");
      out.write("                            <li><a href=\"#\">1:1 문의내역</a></li>\r\n");
      out.write("                        \r\n");
      out.write("                    </div>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"content_2\">\r\n");
      out.write("                <div id=\"content-area\">\r\n");
      out.write("                	\r\n");
      out.write("                  \r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div><!--content-->\r\n");
      out.write("\r\n");
      out.write("        <br><!-- content영역과 footer영역 사이 띄우기-->\r\n");
      out.write("\r\n");
      out.write("        <div id=\"footer\">\r\n");
      out.write("        </div><!--footer-->\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
